Add artifacts to GitHub Actions pipeline
ventaquil/hashcat pull request #5
Opened 2022-07-14 16:12 UTC by mdawsonuk

2022-07-14 17:34 UTC, ventaquil requested changes

2022-07-14 17:34 UTC, ventaquil commented on .github/workflows/build.yml
> +              hashcat*
Do not exclude `libhashcat.so.*` files.

```suggestion
              hashcat*
              libhashcat*
```

2022-07-14 17:34 UTC, ventaquil commented on .github/workflows/build.yml
> +          path: ${{ env.include_paths }}
Instead of names like `hashcat-macos-latest-0` or `hashcat-ubuntu-latest-1` use more appropriate names like `Hashcat-Linux-Static` or `Hashcat-MacOS-Shared`.

```suggestion
      - name: Generate static artifacts
        if: ${{ matrix.shared == 0 }}
        uses: actions/upload-artifact@v3
        with:
          name: Hashcat-${{ runner.os }}-Static
          path: ${{ env.include_paths }}
      - name: Generate shared artifacts
        if: ${{ matrix.shared == 1 }}
        uses: actions/upload-artifact@v3
        with:
          name: Hashcat-${{ runner.os }}-Shared
          path: ${{ env.include_paths }}
```

2022-07-14 17:36 UTC, ventaquil commented
Accept (or edit) my suggestions please, you can check test actions run here - https://github.com/ventaquil/hashcat/actions.

2022-07-14 17:44 UTC, mdawsonuk commented
Will do, I'll probably bundle in my build-win.yaml file into this PR too, getting it working via WSL

2022-07-14 17:49 UTC, ventaquil commented
Okay, let me know when PR will be ready. Thanks!

2022-07-14 18:31 UTC, mdawsonuk commented
@ventaquil Let me know if the WSL build passes for you on your branch 👍🏻

2022-07-14 19:45 UTC, mdawsonuk commented
Can confirm build is successful and functional on the latest hashcat master branch 👍🏻

2022-07-14 23:17 UTC, ventaquil commented
Here you have results for this actions so unfortunately it's not working 😢 - https://github.com/ventaquil/hashcat/runs/7347949083.

After many tries finally I have got configuration which is working very well.

```yaml
name: Build

env:
  include_paths: |
    charsets/
    docs/
    extra/
    layouts/
    masks/
    modules/
    OpenCL/
    rules/
    example*
    hashcat*
    libhashcat*

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - 'OpenCL/**.h'
      - 'OpenCL/**.cl'
      - 'include/**.h'
      - 'src/**.c'
      - 'tools/**'
      - '**/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'OpenCL/**.h'
      - 'OpenCL/**.cl'
      - 'include/**.h'
      - 'src/**.c'
      - 'tools/**'
      - '**/Makefile'
      - '.github/workflows/build.yml'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        shared: [0, 1]
    name: Build Linux (${{ matrix.shared == 0 && 'Static' || 'Shared' }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          SHARED: ${{ matrix.shared }}
        run: make
      - name: Generate artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Hashcat-${{ runner.os }}-${{ matrix.shared == 0 && 'Static' || 'Shared' }}
          path: ${{ env.include_paths }}

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        shared: [0, 1]
    name: Build MacOS (${{ matrix.shared == 0 && 'Static' || 'Shared' }})
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          SHARED: ${{ matrix.shared }}
        run: make
      - name: Generate artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Hashcat-${{ runner.os }}-${{ matrix.shared == 0 && 'Static' || 'Shared' }}
          path: ${{ env.include_paths }}

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        shared: [0, 1]
    name: Build Windows (${{ matrix.shared == 0 && 'Static' || 'Shared' }})
    runs-on: windows-latest
    steps:
      - name: Install libiconv
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            gcc
            git
            libiconv
            libiconv-devel
            make
      - uses: actions/checkout@v3
      - name: Build
        shell: msys2 {0}
        env:
          SHARED: ${{ matrix.shared }}
        run: make
      - name: Generate artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Hashcat-${{ runner.os }}-${{ matrix.shared == 0 && 'Static' || 'Shared' }}
          path: ${{ env.include_paths }}
```

See https://github.com/ventaquil/hashcat/runs/7349471789 for results.

2022-07-14 23:22 UTC, merged

2022-07-14 23:23 UTC, ventaquil commented
Thanks for suggestion with artifacts, I didn't know about that.

2022-07-15 08:44 UTC, mdawsonuk commented
That's weird, it worked fine for me https://github.com/mdawsonuk/hashcat/actions/runs/2672639293

Oh well, at least it's building for Windows now